---
title: "Zane_Alderfer_IST772_Final"
author: "Zane"
date: "2023-09-16"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
#question1
library(readxl)
schoolvax = read_excel('schoolvax.xlsx')
public_dummy <- ifelse(schoolvax$pubpriv == "PUBLIC", 1, 0)
hi_enrollment <- ifelse(schoolvax$enrollment > mean(schoolvax$enrollment),1, 0)
relig_exempt <- ifelse(schoolvax$religious > 0, 1, 0)
```
dummy variables created above
```{r}
#question2
public_dummy_mean <- mean(public_dummy)
hi_enrollment_mean <- mean(hi_enrollment)
relig_exempt_mean <- mean(relig_exempt)
show(public_dummy_mean)
show(hi_enrollment_mean)
show(relig_exempt_mean)
```
means for dummy variables above
```{r}
#question3
library(BayesFactor)
linear_regression <- lm(medical ~ pubpriv + enrollment, data = schoolvax)
BF_linear_regression <- lmBF(medical ~ pubpriv + enrollment, data = schoolvax, posterior = TRUE, iterations = 10000)
summary(linear_regression)
summary(BF_linear_regression)
```
```{r}
#question5
library(mcmc)
library(MCMCpack)
logistic_model <- glm(relig_exempt ~ public_dummy + hi_enrollment, family = binomial(),
                   data = schoolvax)
summary(logistic_model)
exp(coef(logistic_model))
vax_mcmc <- MCMClogit(formula = relig_exempt ~ public_dummy + hi_enrollment,
                    data = schoolvax)
summary(vax_mcmc)
plot(vax_mcmc)
```

